tema = 'DarkPurple7'
tema_aviso = 'DarkRed'
fonte_texto = ('Sans-Serif', 15)
fonte_titulo = ('Impact', 20)
cor = 'white'
tamanho = (20, 1)
tamanho_janela = (400, 380)
background_listas = '#232B5C'
poltrona_image = './images/poltrona.png'
fundo_image = './images/fundo.png'
icone_image = './images/icone.ico'
